export const profile = {
  name: 'Kamalakar Reddy Gorantla', shortName: 'Kamalakar Reddy Gorantla',
  email: 'gorantlakamalakarreddharhi@gmail.com',
  github: 'https://github.com/kl987456', linkedin: 'https://linkedin.com/in/kamalakar-reddy',
  resume: '/Gorantla_Kamalakar_Reddy_Resume.pdf',
};
export const projects = [
  {
    slug:'workforce-ai', name:'Workforce AI', category:'Voice AI · Recruiting', color:'#c8eb66', ink:'#1c281c',
    image:'/images/portfolio-library/scene-workforce-ai.png',
    tag:'Full-stack application', metric:'08', metricLabel:'Rule-based automations',
    headline:'Autonomous Voice AI Screening & Talent Pipeline Orchestration.',
    summary:'Production-grade recruiting console combining semantic candidate discovery, automated outreach, and telephony voice screening with 8 stateful automations.',
    description:'I built the React and TypeScript frontend and FastAPI backend for a voice-AI recruiting platform. Requisitions, ranked talent search, candidate reachout, and Hunar phone-screening results come together in one workflow.',
    repo:'https://github.com/kl987456/workforce-ai-custom', live:'https://workforce-ai-final.vercel.app',
    stack:['FastAPI','React','TypeScript','Tailwind','asyncpg','Neon Postgres','Vite','Framer Motion','Three.js','Hunar Voice AI'],
    flow:['Requisition','Talent search','Voice screen','Signed events','Pipeline update'],
    features:[['One consistent call record','Reconciles call status, recordings, results, and summaries arriving as separate asynchronous events.'],['Automation with explicit rules','Eight rule-based workflows handle actions such as new-candidate dialing, triage, retries, cross-pipeline sync, and do-not-contact suppression.'],['Verification before state changes','HMAC-SHA256 signature and timestamp checks protect call-state updates from untrusted webhook requests.']],
    boundary:'Production deployment integrates with enterprise telephony APIs, Redis event queues, and KMS-encrypted credentials. Demonstration uses seeded candidate corpora and verified HMAC webhook authentication.',
    evidence:'api/app/routers/autonomous.py', branch:'master',
  },
  {
    slug:'forgeguard', name:'ForgeGuard', category:'Agent systems · Software engineering', color:'#ee633f', ink:'#25130d',
    image:'/images/portfolio-library/scene-forgeguard.png',
    tag:'Working workflow prototype', metric:'05', metricLabel:'Artifacts in a review package',
    headline:'Supervised Multi-Agent Engineering with Explicit Human Gatekeeping.',
    summary:'Autonomous software engineering workflow coordinating repository analysis, planning, patch proposals, and review packages with deterministic human approval.',
    description:'ForgeGuard explores the boundary between useful engineering assistance and unchecked autonomy. A supervisor coordinates repository analysis, planning, patch proposals, test proposals, and review. The result is inspectable before a person approves or rejects it.',
    repo:'https://github.com/kl987456/autonomous-software-engineering-agent', live:null,
    stack:['Python','FastAPI','Next.js','JWT','Docker','Pytest'],
    flow:['Issue','Repository analysis','Plan + proposals','Review package','Human decision'],
    features:[['Five inspectable artifacts','Packages analysis, a plan, patch and test previews, and a review summary instead of hiding the handoffs.'],['A bounded workflow','A configured repository root, file-extension boundaries, a file-inventory ceiling, and limited review rounds keep the demonstration scoped.'],['An explicit approval state','JWT-protected routes record the human approve-or-reject decision. Approval changes workflow state; it does not silently execute a patch.']],
    boundary:'Operates within sandboxed repository environments with strict AST file boundaries. Production roadmap includes Redis queue workers and Git provider webhooks.',
    evidence:'backend/workflow.py', branch:'main',
  },
  {
    slug:'aperture', name:'Aperture', category:'Agent systems · Data analysis', color:'#9eafda', ink:'#182139',
    image:'/images/portfolio-library/scene-aperture.png',
    tag:'Working analytics prototype', metric:'500', metricLabel:'Default result row cap',
    headline:'Traced SQL Analytics Engine with Abstract Syntax Tree Validation.',
    summary:'Autonomous analytics pipeline translating natural language into validated SQL, evidence datasets, and executive chart visualisations.',
    description:'Aperture brings planning, SQL validation, execution, and analysis into a traced multi-agent workflow. It works against a bundled sales schema, with an offline planner for regional revenue, quarterly trends, and product performance, plus an optional OpenAI planner.',
    repo:'https://github.com/kl987456/autonomous-data-analyst', live:null,
    stack:['FastAPI','Next.js','JWT','PostgreSQL','SQLGlot','SQLAlchemy','Pandas'],
    flow:['Question','Schema + planning','AST validation','Read query','Evidence + chart'],
    features:[['Inspect the query structure','SQLGlot parses the query tree to reject multiple statements and mutation nodes, then normalizes a result-row limit.'],['Keep answers tied to rows','The workflow retains evidence rows alongside the Pandas summary, chart specification, and agent trace.'],['Repair within a limit','Query repair is bounded. The demonstration is scoped to a known sales schema rather than claiming to answer every business question.']],
    boundary:'SQL execution is constrained to read-only analytical queries with row capping and query AST sanitization via SQLGlot.',
    evidence:'backend/app/sql_safety.py', branch:'main',
  },
  {
    slug:'researchforge', name:'ResearchForge', category:'Agent systems · Research orchestration', color:'#d4c1e5', ink:'#32223d',
    image:'/images/portfolio-library/scene-researchforge.png',
    tag:'Working orchestration prototype', metric:'03', metricLabel:'Parallel specialist channels',
    headline:'Concurrent Multi-Agent Research Orchestration with Bounded Synthesis.',
    summary:'Distributed research system coordinating parallel specialist agent channels, evidence scoring, iterative synthesis, and bounded critique.',
    description:'ResearchForge makes agent collaboration visible. A supervisor selects web, document, and database channels, runs them concurrently, and passes their outputs through filtering, synthesis, and a critic. Traces expose handoffs and timings throughout the run.',
    repo:'https://github.com/kl987456/autonomous-multi-agent-research', live:null,
    stack:['Python','FastAPI','Next.js','JWT','OpenAI Responses API','Docker'],
    flow:['Research brief','Parallel channels','Evidence filter','Synthesis','Bounded critique'],
    features:[['Real parallel orchestration','Specialist channels run concurrently using explicit Python orchestration and return typed results to the supervisor.'],['Repeatable evaluation','A deterministic mock provider and versioned evaluation harness make the demonstration repeatable without live API spending.'],['Make revision finite','The critic checks report completeness and evidence count, with at most two synthesis rounds by default.']],
    boundary:'Specialist channels execute concurrently under supervisor timeouts. Critic passes are bounded to two evaluation cycles.',
    evidence:'backend/app/workflow.py', branch:'main',
  },
  {
    slug:'atlas', name:'Atlas', category:'Agent systems · Knowledge retrieval', color:'#f2c94c', ink:'#2b2107',
    image:'/images/portfolio-library/scene-atlas.png',
    tag:'Working retrieval prototype', metric:'06', metricLabel:'Specialist agent roles',
    headline:'Self-Correcting Agentic RAG with Bidirectional Citation Validation.',
    summary:'Citation-first retrieval-augmented generation workflow with pre-generation relevance grading and source verification.',
    description:'Atlas is a citation-first RAG workflow for company knowledge questions. A supervisor routes shared state through query understanding, retrieval, relevance grading with bounded retry, answer generation, hallucination checking, and citation validation—so an answer either ships with sources or the system says so.',
    repo:'https://github.com/kl987456/autonomous-agentic-rag', live:null,
    stack:['FastAPI','Next.js','PostgreSQL','pgvector','Redis','Docker'],
    flow:['Question','Retrieval','Bounded grading','Answer draft','Citations verified'],
    features:[['Grading before generation','A relevance grader checks retrieved context before the answer agent ever runs, retrying retrieval within a hard budget rather than answering on weak evidence.'],['Citations are validated, not assumed','A dedicated citation-validation agent checks the answer against its sources before it reaches the interface.'],['Bounded, not endless, retries','Retrieval expansion is capped so an underspecified question fails clearly instead of looping.']],
    boundary:'Evaluates retrieval quality against semantic thresholds before answer synthesis; citations are strictly mapped to verified document chunk IDs.',
    evidence:'app/workflow.py', branch:'main',
  },
];
export type Project = typeof projects[number];
export const gallery: {w:number;h:number;title:string;kind:string;wide:boolean;caption:string;scene:string}[] = [
  {w:1536,h:1024,title:'Particle flow',kind:'INTERACTIVE STUDY',wide:true,caption:'Two particle streams meet and swirl.',scene:'rasengan-chidori'},
  {w:1536,h:1024,title:'Radial motion',kind:'INTERACTIVE STUDY',wide:true,caption:'A study in symmetry, rotation, and expanding forms.',scene:'iron-man'},
  {w:1536,h:1024,title:'Light trails',kind:'INTERACTIVE STUDY',wide:true,caption:'Branching light moves through a field of rotating rings.',scene:'thor'},
];
// Every repo below is real, publicly on github.com/kl987456, ordered by technical substance (strongest first).
export const otherWork = [
  {name:'RLHF / DPO Alignment Platform', category:'Agentic AI', blurb:'An end-to-end platform for aligning language models with human feedback: preference annotation, SFT with QLoRA, a Bradley-Terry reward model, and Direct Preference Optimization, served through FastAPI, Celery, and Redis.', tech:'Python · FastAPI · PyTorch · Transformers · PEFT · TRL', repo:'https://github.com/kl987456/P5-rlhf-dpo-platform'},
  {name:'Cortex Prime Workflow Builder', category:'Agentic AI', blurb:'An AI agent orchestration terminal for building text-processing pipelines out of specialised agents (sanitizer, briefer, analyst), with multi-LLM fallback across Gemini and Hugging Face, and a Vitest/Playwright test suite.', tech:'Next.js · TypeScript · Framer Motion · Vitest · Playwright', repo:'https://github.com/kl987456/Assignment.Workflow-Builder'},
  {name:'Multilingual Speaker Diarization & Transcription', category:'ML & Audio', blurb:'A speech pipeline that separates speakers (VAD, ECAPA-TDNN embeddings, clustering) and transcribes them across languages with Whisper, confidence scoring, and a human-review API.', tech:'Python · FastAPI · Celery · Whisper · SpeechBrain', repo:'https://github.com/kl987456/P1-multilingual-diarization'},
  {name:'Document Layout Intelligence', category:'ML & Vision', blurb:'An OCR pipeline (PaddleOCR + Tesseract) that uses LayoutLMv3 and a DETR-based table detector to pull structured regions, key-value pairs, and tables out of PDFs and images as JSON.', tech:'Python · FastAPI · Celery · LayoutLMv3 · DETR', repo:'https://github.com/kl987456/P2-document-layout-intelligence'},
  {name:'Real-Time Anomaly Detection System', category:'Backend & Streams', blurb:'Ingests metrics over Kafka or Prometheus scraping and runs three anomaly-detection algorithms in parallel — Z-score, Isolation Forest, and an LSTM autoencoder — alerting to Slack and PagerDuty with Grafana dashboards.', tech:'Python · FastAPI · Kafka · scikit-learn · PyTorch', repo:'https://github.com/kl987456/P6-anomaly-detection'},
  {name:'Indic LLM Evaluation Framework', category:'Agentic AI', blurb:'A benchmark harness for LLM performance on Indic languages, with adapters for OpenAI, Anthropic, HuggingFace, and Ollama, plus exact-match, ROUGE-L, BERTScore, LLM-as-judge, and hallucination-detection metrics.', tech:'Python · FastAPI · Transformers · ROUGE / BERTScore', repo:'https://github.com/kl987456/P4-indic-llm-eval'},
  {name:'FairHire AI', category:'Full-Stack AI', blurb:'An explainable, upload-first AI hiring intelligence platform using bring-your-own-key OpenAI analysis.', tech:'Next.js · TypeScript · OpenAI API', repo:'https://github.com/kl987456/fairhire-ai'},
  {name:'FinSight — AI Personal Finance Coach', category:'Full-Stack AI', blurb:'A full-stack financial advisor where demo personas track expenses, manage investments, and get AI-driven coaching through OpenAI and Perplexity.', tech:'FastAPI · Python · React · OpenAI GPT-4', repo:'https://github.com/kl987456/finsight-ai'},
  {name:'TaskFlow — Role-Based Coordination', category:'Backend & APIs', blurb:'Coordinates team projects with role-based access control (Admin/Member), task tracking, dashboards, and activity logs.', tech:'React · Node.js/Express · PostgreSQL · JWT', repo:'https://github.com/kl987456/taskflow-project-management'},
  {name:'ML Experiment Tracker', category:'ML & Systems', blurb:'A self-hosted experiment-tracking platform with a Python SDK, FastAPI/gRPC metrics ingestion, and Celery-based drift detection — a lightweight alternative to MLflow or Weights & Biases.', tech:'Python · FastAPI · gRPC · React', repo:'https://github.com/kl987456/P3-ml-experiment-tracker'},
  {name:'SMATE — Smart Tutor Platform (API)', category:'Backend & APIs', blurb:'A GraphQL API (Apollo Server, Prisma, Auth0) powering SMATE, the EdTech tutoring concept behind the Smart Tutor proof of concept I built at Terralogic.', tech:'Node.js · Apollo Server · Prisma · Auth0', repo:'https://github.com/kl987456/smate-backend'},
  {name:'SMATE — Smart Tutor Platform (UI)', category:'Full-Stack AI', blurb:'The Next.js interface for SMATE, authenticated through Auth0 and driven by the GraphQL API above.', tech:'Next.js · Auth0 · GraphQL', repo:'https://github.com/kl987456/smate-frontend'},
  {name:'Career Counselor AI', category:'Full-Stack AI', blurb:'An AI career counselor users talk through career questions with, with session management and a tRPC/Prisma backend.', tech:'Next.js · tRPC · Prisma · OpenAI GPT', repo:'https://github.com/kl987456/career-counselor-ai'},
  {name:'Vibe Coder Guardrails', category:'Agentic AI', blurb:'A set of markdown prompts, decision trees, and checklists that walk AI coding assistants through structured PRD, architecture, and security steps before they generate code.', tech:'Prompt engineering / process design', repo:'https://github.com/kl987456/vibe-assistant'},
  {name:'Healthcare Records API', category:'Backend & APIs', blurb:'A Django REST Framework backend with JWT authentication, providing CRUD APIs for patients, doctors, and doctor-patient records, backed by PostgreSQL. Built during my WhatBytes backend internship.', tech:'Python · Django REST Framework · PostgreSQL', repo:'https://github.com/kl987456/whatbytes-backend-assignment'},
  {name:'Credits Management API', category:'Backend & APIs', blurb:'A FastAPI backend tracking per-user credits with a scheduled daily top-up job, also built during my WhatBytes internship.', tech:'Python · FastAPI · PostgreSQL', repo:'https://github.com/kl987456/backend-intern-credits'},
  {name:'LawVriksh Blog API', category:'Backend & APIs', blurb:'A FastAPI blog backend with JWT auth, posts, comments, and likes, from the same internship.', tech:'Python · FastAPI · SQLAlchemy', repo:'https://github.com/kl987456/backend-intern-crud'},
  {name:'Bitespeed Identity Reconciliation', category:'Backend & APIs', blurb:'Links customer contact records that share an email or phone number into a single unified identity.', tech:'Node.js · Express · SQLite', repo:'https://github.com/kl987456/bitespeed-identity-reconciliation'},
  {name:'Redis-Backed Real-Time Messaging', category:'Backend & Streams', blurb:'Real-time chat using an embedded Redis server for message storage and pub/sub over Server-Sent Events.', tech:'Spring Boot · Redis · React', repo:'https://github.com/kl987456/Assignment-2'},
  {name:'Toll Plaza Finder API', category:'Backend & APIs', blurb:'A REST API that finds toll plazas between two Indian pincodes using Google Maps geocoding and an in-memory database of 2,387 toll plazas.', tech:'Java · Spring Boot · Google Maps API', repo:'https://github.com/kl987456/Assignment-1'},
  {name:'Event-Driven Order Processing', category:'Backend & Streams', blurb:'Simulates order creation, payment, shipping, and cancellation using the Observer pattern to log and alert on status changes.', tech:'Java · Design Patterns', repo:'https://github.com/kl987456/order-processing-system'},
  {name:'API Security Framework', category:'Backend & APIs', blurb:'A Django backend built around API security, rate limiting, and access-control concerns.', tech:'Python · Django · Cryptography', repo:'https://github.com/kl987456/secureapi-project'},
  {name:'PhishCoop Machine Learning', category:'ML & Vision', blurb:'Trains and compares Logistic Regression, SVM, and Random Forest classifiers on a UCI phishing-website dataset, reaching about 97% accuracy with Random Forest.', tech:'Python · scikit-learn · Pandas', repo:'https://github.com/kl987456/detecting-phishing-websites-by-machine-learning'},
];

// Hobbies & personal pursuits: 35mm photography alongside visual and athletic studies.
export const hobbies = [
  // 35mm photography of Kamalakar
  {src:'/images/kamalakar-original.jpg',w:1200,h:1600,group:'REAL ME',title:'Kamalakar Reddy Gorantla',caption:'AI systems engineer — engineering profile, Bengaluru.',wide:false,isRaw:true},
  {src:'/images/riverside.jpg',w:1600,h:1200,group:'REAL ME',title:'Riverside',caption:'Riverside downtime outside engineering hours.',wide:true,isRaw:true},
  {src:'/images/rooftop.jpg',w:1200,h:1600,group:'REAL ME',title:'Bengaluru Skyline',caption:'City skyline at dusk.',wide:false,isRaw:true},
  {src:'/images/temple.jpg',w:1200,h:1600,group:'REAL ME',title:'Temple Architecture',caption:'Morning architectural exploration.',wide:false,isRaw:true},

  // Visual Studies (including former gallery editorial illustrations)
  {src:'/images/portfolio-library/P02-green-collar-hero.png',w:1536,h:1024,group:'VISUAL STUDIES',title:'Luminous Signal',caption:'Cinematic lighting and high-contrast character study.',wide:true,isRaw:false},
  {src:'/images/portfolio-library/P05-artwork.png',w:1536,h:1024,group:'VISUAL STUDIES',title:'Systems in Pencil',caption:'Architectural graphite illustration with cooperating agent networks.',wide:true,isRaw:false},
  {src:'/images/portfolio-library/P08-artwork.png',w:1536,h:1024,group:'VISUAL STUDIES',title:'Tactile System Print',caption:'Linocut and risograph print study of autonomous engineering workflows.',wide:true,isRaw:false},
  {src:'/images/portfolio-library/P09-artwork.png',w:1536,h:1024,group:'VISUAL STUDIES',title:'Architecture of Thought',caption:'Cut-paper surrealist study visualizing distributed agent topologies.',wide:true,isRaw:false},
  {src:'/images/portfolio-library/P12-artwork.png',w:1536,h:1024,group:'VISUAL STUDIES',title:'Autonomous Ensemble',caption:'Fashion sketch study presenting AI agents as a collaborative engineering team.',wide:true,isRaw:false},

  // Athletic and lifestyle studies
  {src:'/images/hobbies/riding-mountain-pass.jpg',w:1600,h:900,group:'RIDING',title:'Mountain Pass',caption:'High-altitude motorcycle touring and mountain routes.',wide:true,isRaw:false},
  {src:'/images/hobbies/riding-coast-road.jpg',w:1600,h:900,group:'RIDING',title:'Coastal Route',caption:'Coastal endurance riding and long-distance touring.',wide:false,isRaw:false},
  {src:'/images/hobbies/cricket-bowling.jpg',w:1600,h:900,group:'CRICKET',title:'Bowling Technique',caption:'Pace bowling mechanics and line-and-length practice.',wide:false,isRaw:false},
  {src:'/images/hobbies/cricket-batting.jpg',w:1600,h:900,group:'CRICKET',title:'Shot Execution',caption:'Off-drive execution and stroke timing.',wide:false,isRaw:false},
  {src:'/images/hobbies/chess-mountain-terrace.jpg',w:1600,h:900,group:'CHESS',title:'Positional Analysis',caption:'Classical opening variations and middlegame strategy.',wide:false,isRaw:false},
  {src:'/images/hobbies/chess-rooftop-city.jpg',w:1600,h:900,group:'CHESS',title:'Tactical Endgame',caption:'Calculating endgame combinations and calculation depth.',wide:true,isRaw:false},
  {src:'/images/hobbies/street-dogs.jpg',w:1600,h:900,group:'STREET DOGS',title:'Community Welfare',caption:'Community animal welfare and evening rounds.',wide:true,isRaw:false},
  {src:'/images/hobbies/fitness-terrace.jpg',w:1600,h:900,group:'TRAINING',title:'Strength Conditioning',caption:'Strength training and functional conditioning.',wide:false,isRaw:false},
  {src:'/images/hobbies/fitness-gym.jpg',w:1600,h:900,group:'TRAINING',title:'Training Discipline',caption:'Daily resistance training regimen.',wide:false,isRaw:false},
  {src:'/images/hobbies/sneakers.jpg',w:1600,h:900,group:'SNEAKERS',title:'Industrial Design',caption:'Appreciation of industrial design, materials, and silhouettes.',wide:false,isRaw:false},
  {src:'/images/hobbies/gaming-night.jpg',w:1600,h:900,group:'GAMING',title:'Interactive Systems',caption:'Exploring world architecture, game physics, and narrative design.',wide:false,isRaw:false},
  {src:'/images/hobbies/worldbuilding.jpg',w:1600,h:900,group:'WORLDBUILDING',title:'Generative Architecture',caption:'Exploring computational generative architecture and spatial environments.',wide:true,isRaw:false},
  {src:'/images/hobbies/ai-studio.jpg',w:1600,h:900,group:'THE STUDIO',title:'Engineering Studio',caption:'Optimized workstation layout for deep-work systems engineering.',wide:false,isRaw:false},
];
export type Hobby = typeof hobbies[number];
